package com.devon.isearch

import com.devon.isearch.datasource.IRequester
import com.devon.isearch.datasource.iTunesSource
import com.devon.isearch.mocks.MockRequester
import com.devon.isearch.model.types.Movie
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Before
import org.junit.Test
import org.koin.core.context.startKoin
import org.koin.core.context.stopKoin
import org.koin.dsl.module
import org.koin.test.KoinTest

class iTunesSourceTest: KoinTest {

    @Before
    fun setup(){
        val module = module {
            single<IRequester> {
                MockRequester("\n" +
                        "{\n" +
                        " \"resultCount\":6,\n" +
                        " \"results\": [\n" +
                        "{\"wrapperType\":\"track\", \"kind\":\"feature-movie\", \"collectionId\":1135567087, \"trackId\":251188802, \"artistName\":\"Roland Emmerich\", \"collectionName\":\"Big Action 10-Film Collection\", \"trackName\":\"Stargate\", \"collectionCensoredName\":\"Big Action 10-Film Collection\", \"trackCensoredName\":\"Stargate\", \"collectionArtistId\":345356312, \"collectionArtistViewUrl\":\"https://itunes.apple.com/us/artist/lions-gate-films-inc/345356312?uo=4\", \"collectionViewUrl\":\"https://itunes.apple.com/us/movie/stargate/id251188802?uo=4\", \"trackViewUrl\":\"https://itunes.apple.com/us/movie/stargate/id251188802?uo=4\", \n" +
                        "\"previewUrl\":\"https://video-ssl.itunes.apple.com/itunes-assets/Video128/v4/c5/5b/6d/c55b6d93-8694-c551-57e8-6f80f6ff4cfb/mzvf_5951008932067403317.640x352.h264lc.U.p.m4v\", \"artworkUrl30\":\"https://is4-ssl.mzstatic.com/image/thumb/Video1/v4/9c/d2/a5/9cd2a5e5-4710-abf4-925f-377e1666b0de/source/30x30bb.jpg\", \"artworkUrl60\":\"https://is4-ssl.mzstatic.com/image/thumb/Video1/v4/9c/d2/a5/9cd2a5e5-4710-abf4-925f-377e1666b0de/source/60x60bb.jpg\", \"artworkUrl100\":\"https://is4-ssl.mzstatic.com/image/thumb/Video1/v4/9c/d2/a5/9cd2a5e5-4710-abf4-925f-377e1666b0de/source/100x100bb.jpg\", \"collectionPrice\":7.99, \"trackPrice\":7.99, \"collectionHdPrice\":9.99000, \"trackHdPrice\":9.99000, \"releaseDate\":\"1994-10-28T07:00:00Z\", \"collectionExplicitness\":\"notExplicit\", \"trackExplicitness\":\"notExplicit\", \"discCount\":1, \"discNumber\":1, \"trackCount\":10, \"trackNumber\":6, \"trackTimeMillis\":7268355, \"country\":\"USA\", \"currency\":\"USD\", \"primaryGenreName\":\"Sci-Fi & Fantasy\", \"contentAdvisoryRating\":\"PG-13\", \n" +
                        "\"longDescription\":\"A small group of US troups and an Egyptologist use an ancient device found in 1920's Egypt to transport themselves to a distant planet where humans resemble ancient Egyptians.\", \"hasITunesExtras\":true}, \n" +
                        "{\"wrapperType\":\"track\", \"kind\":\"feature-movie\", \"trackId\":284837871, \"artistName\":\"Martin Wood\", \"trackName\":\"Stargate: Continuum\", \"trackCensoredName\":\"Stargate: Continuum\", \"trackViewUrl\":\"https://itunes.apple.com/us/movie/stargate-continuum/id284837871?uo=4\", \n" +
                        "\"previewUrl\":\"https://video-ssl.itunes.apple.com/itunes-assets/Video128/v4/a6/03/18/a60318d9-74b7-05df-aaa1-76555dc5099f/mzvf_6409598175694399365.640x358.h264lc.U.p.m4v\", \"artworkUrl30\":\"https://is5-ssl.mzstatic.com/image/thumb/Video62/v4/aa/a7/de/aaa7de94-57a8-8b9b-1a13-dd3c3746d22a/source/30x30bb.jpg\", \"artworkUrl60\":\"https://is5-ssl.mzstatic.com/image/thumb/Video62/v4/aa/a7/de/aaa7de94-57a8-8b9b-1a13-dd3c3746d22a/source/60x60bb.jpg\", \"artworkUrl100\":\"https://is5-ssl.mzstatic.com/image/thumb/Video62/v4/aa/a7/de/aaa7de94-57a8-8b9b-1a13-dd3c3746d22a/source/100x100bb.jpg\", \"collectionPrice\":14.99, \"trackPrice\":14.99, \"trackRentalPrice\":3.99000, \"collectionHdPrice\":14.99000, \"trackHdPrice\":14.99000, \"trackHdRentalPrice\":3.99000, \"releaseDate\":\"2008-07-29T07:00:00Z\", \"collectionExplicitness\":\"notExplicit\", \"trackExplicitness\":\"notExplicit\", \"trackTimeMillis\":5920670, \"country\":\"USA\", \"currency\":\"USD\", \"primaryGenreName\":\"Sci-Fi & Fantasy\", \"contentAdvisoryRating\":\"PG\", \n" +
                        "\"longDescription\":\"An elite military unit (SG-1) must flee back to Earth when two members of their team inexplicably disappear into thin air. But they return to a world in which the Stargate -- an Ancient device which allows them to travel to hundreds of planets -- was never discovered, and their own history has been erased. Now they must convince a dubious government and military that the timeline was altered by a powerful Alien enemy (Ba'al) in order to conquer Earth, and time is not on their side.\"}, \n" +
                        "{\"wrapperType\":\"track\", \"kind\":\"feature-movie\", \"trackId\":276879622, \"artistName\":\"Robert C. Cooper\", \"trackName\":\"Stargate: The Ark of Truth\", \"trackCensoredName\":\"Stargate: The Ark of Truth\", \"trackViewUrl\":\"https://itunes.apple.com/us/movie/stargate-the-ark-of-truth/id276879622?uo=4\", \n" +
                        "\"previewUrl\":\"https://video-ssl.itunes.apple.com/itunes-assets/Video118/v4/a3/2a/34/a32a3414-7c76-e97c-94be-0c925db73c60/mzvf_3428982124199243787.640x478.h264lc.U.p.m4v\", \"artworkUrl30\":\"https://is1-ssl.mzstatic.com/image/thumb/Video62/v4/67/37/a9/6737a9d1-2103-03de-4c5c-a46fc4e796ef/source/30x30bb.jpg\", \"artworkUrl60\":\"https://is1-ssl.mzstatic.com/image/thumb/Video62/v4/67/37/a9/6737a9d1-2103-03de-4c5c-a46fc4e796ef/source/60x60bb.jpg\", \"artworkUrl100\":\"https://is1-ssl.mzstatic.com/image/thumb/Video62/v4/67/37/a9/6737a9d1-2103-03de-4c5c-a46fc4e796ef/source/100x100bb.jpg\", \"collectionPrice\":14.99, \"trackPrice\":14.99, \"trackRentalPrice\":3.99000, \"collectionHdPrice\":14.99000, \"trackHdPrice\":14.99000, \"trackHdRentalPrice\":3.99000, \"releaseDate\":\"2008-03-11T07:00:00Z\", \"collectionExplicitness\":\"notExplicit\", \"trackExplicitness\":\"notExplicit\", \"trackTimeMillis\":6117617, \"country\":\"USA\", \"currency\":\"USD\", \"primaryGenreName\":\"Sci-Fi & Fantasy\", \"contentAdvisoryRating\":\"PG\", \n" +
                        "\"longDescription\":\"Lt. Colonel Cameron Mitchell, Lt. Colonel Samantha Carter, Dr. Daniel Jackson, Vala Mal Doran and the alien, Tealc, all members of the elite Stargate SG-1 team, travel to the ruins of Dakara in hopes of finding the fabled Ark of Truth. Built by the Alterans, (builders of the stargates), millions of years before, this ancient artifact may be the sole means remaining to defeat the Ori armies who have thus far proven unstoppable in their quest to conquer the universe in the name of their religion, Origin.\"}, \n" +
                        "{\"wrapperType\":\"track\", \"kind\":\"feature-movie\", \"trackId\":1382373515, \"artistName\":\"Mercedes Bryce Morgan\", \"trackName\":\"Stargate Origins: Catherine\", \"trackCensoredName\":\"Stargate Origins: Catherine\", \"trackViewUrl\":\"https://itunes.apple.com/us/movie/stargate-origins-catherine/id1382373515?uo=4\", \n" +
                        "\"previewUrl\":\"https://video-ssl.itunes.apple.com/itunes-assets/Video115/v4/7e/ca/f3/7ecaf366-0aa2-d8f2-1ad3-169ec45b750f/mzvf_727003259881577379.640x424.h264lc.U.p.m4v\", \"artworkUrl30\":\"https://is5-ssl.mzstatic.com/image/thumb/Video125/v4/48/a4/04/48a40435-21c1-e370-a199-7523735918bf/source/30x30bb.jpg\", \"artworkUrl60\":\"https://is5-ssl.mzstatic.com/image/thumb/Video125/v4/48/a4/04/48a40435-21c1-e370-a199-7523735918bf/source/60x60bb.jpg\", \"artworkUrl100\":\"https://is5-ssl.mzstatic.com/image/thumb/Video125/v4/48/a4/04/48a40435-21c1-e370-a199-7523735918bf/source/100x100bb.jpg\", \"collectionPrice\":14.99, \"trackPrice\":14.99, \"trackRentalPrice\":3.99000, \"collectionHdPrice\":14.99000, \"trackHdPrice\":14.99000, \"trackHdRentalPrice\":3.99000, \"releaseDate\":\"2018-06-19T07:00:00Z\", \"collectionExplicitness\":\"notExplicit\", \"trackExplicitness\":\"notExplicit\", \"trackTimeMillis\":6291327, \"country\":\"USA\", \"currency\":\"USD\", \"primaryGenreName\":\"Action & Adventure\", \"contentAdvisoryRating\":\"Unrated\", \"shortDescription\":\"In 1939, Professor Paul Langford and his daughter Catherine are still grappling with the mysteries\", \n" +
                        "\"longDescription\":\"In 1939, Professor Paul Langford and his daughter Catherine are still grappling with the mysteries of the ancient relic they discovered in the Egyptian desert more than ten years ago. With war looming in Europe and funding running out, these brilliant minds are approaching their lowest ebb. Little do they know, answers are about to present themselves in a dangerous form, when the Nazi Occultist Dr. Wilhelm Brücke approaches their facility with a sinister motive. Enlisting the help of two young soldiers, Catherine must use all of her wit and nous as she and her new allies embark on an adventure into the unknown to rescue her father, and save the Earth from an unimaginable darkness.\"}, \n" +
                        "{\"wrapperType\":\"track\", \"kind\":\"feature-movie\", \"trackId\":319839500, \"artistName\":\"Mario Azzopardi\", \"trackName\":\"Stargate: Children of the Gods\", \"trackCensoredName\":\"Stargate: Children of the Gods\", \"trackViewUrl\":\"https://itunes.apple.com/us/movie/stargate-children-of-the-gods/id319839500?uo=4\", \n" +
                        "\"previewUrl\":\"https://video-ssl.itunes.apple.com/itunes-assets/Video114/v4/86/3c/1a/863c1af2-a551-cb72-4011-241bd19a5ab9/mzvf_4388549582509216491.640x480.h264lc.U.p.m4v\", \"artworkUrl30\":\"https://is2-ssl.mzstatic.com/image/thumb/Video/v4/87/73/58/8773580b-8bf2-ed49-8259-710816a71c7c/source/30x30bb.jpg\", \"artworkUrl60\":\"https://is2-ssl.mzstatic.com/image/thumb/Video/v4/87/73/58/8773580b-8bf2-ed49-8259-710816a71c7c/source/60x60bb.jpg\", \"artworkUrl100\":\"https://is2-ssl.mzstatic.com/image/thumb/Video/v4/87/73/58/8773580b-8bf2-ed49-8259-710816a71c7c/source/100x100bb.jpg\", \"collectionPrice\":14.99, \"trackPrice\":14.99, \"trackRentalPrice\":3.99000, \"releaseDate\":\"1997-01-01T08:00:00Z\", \"collectionExplicitness\":\"notExplicit\", \"trackExplicitness\":\"notExplicit\", \"trackTimeMillis\":5532000, \"country\":\"USA\", \"currency\":\"USD\", \"primaryGenreName\":\"Sci-Fi & Fantasy\", \"contentAdvisoryRating\":\"NR\", \n" +
                        "\"longDescription\":\"Col. Jack O'Neill retired from the military a year ago. Just before he left the service, he led an expedition through the stargate, an ancient portal that allows instantaneous travel to other galaxies. He is called back to duty by Gen. Hammond when a group of aliens emerge from the stargate, kill the soldiers guarding it, and kidnap a female guard. After seeing the aftermath of the alien attack and the strange bodies they left behind, O'Neill confesses that he defied the order to destroy Abydos, the world he visited via the stargate. He reveals that Dr. Daniel Jackson, the scientist who was thought to have died on that mission, is alive and living on Abydos. It is also clear that these aliens are not from Abydos. O'Neill is reunited with his old comrades Kawalsky and Ferretti and joined by Capt. Samantha Carter, an astrophysicist. SG-1 returns through the Stargate to Abydos. They discover that Jackson has taken an Abydonian wife, the beautiful Sha're, and that Skaara, the young Abydonian boy whom O'Neill cherishes like a son, has grown into a fine young man. They also see Jackson's latest discovery: a giant cartouche covered in hieroglyphics that seems to be a map of many stargates throughout the galaxy. As they marvel, however, the aliens, led by the handsome but evil Apophis, are making use of a similar map. They emerge from the Stargate on Abydos, and, after a brief battle, kidnap Sha're and Skaara. Ferretti, who was wounded in the firefight with the aliens, has seen the hieroglyphic code that indicates the aliens' destination. O'Neill and Jackson are determined to follow the aliens and to save their loved ones. With a troop of soldiers from Earth in tow, they track the aliens to the planet Chulak. There they discover that Sha're is now Apophis' queen; her body has been taken over by a hideous snake-like creature, one of a species known as the Goa'uld, who rule this planet and collect life-forms from around the galaxy to use as hosts. Jackson and O'Neill know that they can't save Sha're — but can they save themselves and Skaara before they're killed by the Goa'uld's guards and before Gen. Hammond sends a nuclear weapon through the stargate to destroy the planet?\"}, \n" +
                        "{\"wrapperType\":\"track\", \"kind\":\"feature-movie\", \"trackId\":1027567706, \"artistName\":\"William Kraft\", \"trackName\":\"Aliens and Atlantis: Stargates and Hidden Realms\", \"trackCensoredName\":\"Aliens and Atlantis: Stargates and Hidden Realms\", \"trackViewUrl\":\"https://itunes.apple.com/us/movie/aliens-and-atlantis-stargates-and-hidden-realms/id1027567706?uo=4\", \n" +
                        "\"previewUrl\":\"https://video-ssl.itunes.apple.com/itunes-assets/Video122/v4/f9/87/ce/f987ce5e-4ced-a854-0e78-08748d66a216/mzvf_4076010095019083716.640x480.h264lc.U.p.m4v\", \"artworkUrl30\":\"https://is5-ssl.mzstatic.com/image/thumb/Video5/v4/5d/b7/26/5db7262e-89c0-8f57-0030-8d751996a1e1/source/30x30bb.jpg\", \"artworkUrl60\":\"https://is5-ssl.mzstatic.com/image/thumb/Video5/v4/5d/b7/26/5db7262e-89c0-8f57-0030-8d751996a1e1/source/60x60bb.jpg\", \"artworkUrl100\":\"https://is5-ssl.mzstatic.com/image/thumb/Video5/v4/5d/b7/26/5db7262e-89c0-8f57-0030-8d751996a1e1/source/100x100bb.jpg\", \"collectionPrice\":9.99, \"trackPrice\":9.99, \"trackRentalPrice\":3.99000, \"collectionHdPrice\":12.99000, \"trackHdPrice\":12.99000, \"trackHdRentalPrice\":3.99000, \"releaseDate\":\"2015-10-20T07:00:00Z\", \"collectionExplicitness\":\"notExplicit\", \"trackExplicitness\":\"notExplicit\", \"trackTimeMillis\":3624308, \"country\":\"USA\", \"currency\":\"USD\", \"primaryGenreName\":\"Documentary\", \"contentAdvisoryRating\":\"Unrated\", \"shortDescription\":\"Despite being thought of as a myth, the legendary lost city of Atlantis accessed hidden dimensions\", \n" +
                        "\"longDescription\":\"Despite being thought of as a myth, the legendary lost city of Atlantis accessed hidden dimensions and made contact with extraterrestrial races through their highly advanced knowledge of the laws of the universe. Aliens and Atlantis uses new research and insight to expose Atlantis as the pivotal part of our ancient beginnings.\"}]\n" +
                        "}")
            }
        }
        startKoin {
            modules(module)
        }
    }

    @After
    fun cleanup(){
        stopKoin()
    }

    val testExpected = listOf(
        Movie("Stargate"),
        Movie("Stargate: Continuum"),
        Movie("Stargate: The Ark of Truth"),
        Movie("Stargate Origins: Catherine"),
        Movie("Stargate: Children of the Gods"),
        Movie("Aliens and Atlantis: Stargates and Hidden Realms")
    )

    @Test
    fun deSerializeTest(){
        val source = iTunesSource()
        val result = source.getMoviesByName("irrelevant as we just want to test fixed data for serialization")
        assertEquals(testExpected, result)
    }

}